sethome:
  message-show: true
  cooldown: 5
  warmup: 0
  warmup-cancel-on-move: false

home:
  message-show: false
  cooldown: 5
  warmup: 0
  warmup-cancel-on-move: false

deletehome:
  message-show: true
  cooldown: 5
  warmup: 0
  warmup-cancel-on-move: false

extra:
  play-warp-sound: true
  respawn-at-home: true
  check-updates: true
  storage-type: yaml
  max-homes-per-player: 3

messages:
  cmd-sethome: '&2[&a*&2] &aYou now have a new home, &6%player%&a!'
  cmd-home: '&2[&a*&2] &aYou have been teleported to your home, &6%player%&a!'
  cmd-deletehome: '&2[&a*&2] &aYour home has been deleted, &6%player%&a!'
  missing-home: '&4[&cError&4] &cNo home found for &6%player%&c. Use &a/sethome &cto create one!'
  missing-world: '&4[&cError&4] &cThe world for your home no longer exists. Please contact an admin or set a new home.'
  cooldown: '&e[Cooldown] &cYou must wait &6%seconds% &cseconds before using this command again, &6%player%&c.'
  warmup: '&b[Warmup] &7Command will execute in &3%seconds% &7seconds. Please wait...'
  on-move: '&6[Notice] &cYou moved! Command cancelled. Stand still to complete the action.'
  deny-console: '&4[&cError&4] &cThis command can only be used by in-game players.'