# --- SetHome Configuration --- #

# Settings for /sethome
cmd-sethome-message-show: true
cmd-sethome-cooldown: 5
cmd-sethome-warmup: 0
cmd-sethome-warmup-cancel-on-move: false

# Settings for /home
cmd-home-message-show: false
cmd-home-cooldown: 5
cmd-home-warmup: 0
cmd-home-warmup-cancel-on-move: false

# Settings for /deletehome
cmd-deletehome-message-show: true
cmd-deletehome-cooldown: 5
cmd-deletehome-warmup: 0
cmd-deletehome-warmup-cancel-on-move: false

# Extra settings
extra-play-warp-sound: true
extra-respawn-at-home: true
extra-check-updates: true

# Storage type: yaml or sqlite
storage-type: yaml

# Maximum number of homes per player (set to 0 for unlimited)
max-homes-per-player: 3

# Message settings
message-cmd-sethome: '&2[&a*&2] &aYou now have a new home, &6%player%&a!'
message-cmd-home: '&2[&a*&2] &aYou have been teleported to your home, &6%player%&a!'
message-cmd-deletehome: '&2[&a*&2] &aYour home has been deleted, &6%player%&a!'
message-missing-home: '&4[&cError&4] &cNo home found for &6%player%&c. Use &a/sethome &cto create one!'
message-missing-world: '&4[&cError&4] &cThe world for your home no longer exists. Please contact an admin or set a new home.'
message-cooldown: '&e[Cooldown] &cYou must wait &6%seconds% &cseconds before using this command again, &6%player%&c.'
message-warmup: '&b[Warmup] &7Command will execute in &3%seconds% &7seconds. Please wait...'
message-on-move: '&6[Notice] &cYou moved! Command cancelled. Stand still to complete the action.'
message-deny-console: '&4[&cError&4] &cThis command can only be used by in-game players.'
