name: SetHome
version: '${project.version}'
main: com.kingironman.sethome.SetHome
api-version: '1.21'
description: A lightweight SetHome plugin for Bukkit/Spigot
author: KingIronMan2011
commands:
  sethome:
    description: Set your home
  home:
    description: Warp to your home
  deletehome:
    description: Delete your home
  listhome:
    description: List all your home